import type { Metadata } from "next";
import "./globals.css";
import { fontNeue, spaceGrotesk } from "@/assets/fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";




export const metadata: Metadata = {
  title: "Birainy by Farid Mustafayev",
  description: "Generated by Farid Mustafayev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontNeue.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
